Repository chainflip-io/chainflip-backend, pull requests merged in 2023-12, with the labels that each got.

#4292 feat: add redeeming to LP API
  api/bin/chainflip-lp-api/src/main.rs
  api/lib/src/lib.rs
Labels: CLI / API

#4293 feat: try-runtime build to CI
  .cargo/config.toml
  .github/workflows/_20_build.yml
  .github/workflows/ci-main.yml
  .github/workflows/release-berghain.yml
Labels: CI

#4303 fix: CLI redeem amount rounding error
  api/bin/chainflip-cli/src/main.rs
  api/bin/chainflip-cli/src/settings.rs
  state-chain/primitives/src/lib.rs
  utilities/src/with_std.rs
Labels: CLI / API

#4331 Fix: CFE Witnessing, use parent block metadata when decoding events
  engine/src/dot/http_rpc.rs
  engine/src/dot/retry_rpc.rs
  engine/src/dot/rpc.rs
  engine/src/witness/dot.rs
  engine/src/witness/dot/dot_source.rs
Labels: CFE

#4343 feat: Add version cmd to all bins
  Cargo.lock
  api/bin/chainflip-broker-api/Cargo.toml
  api/bin/chainflip-broker-api/README.md
  api/bin/chainflip-broker-api/build.rs
  api/bin/chainflip-broker-api/src/main.rs
  api/bin/chainflip-cli/src/settings.rs
  api/bin/chainflip-ingress-egress-tracker/Cargo.toml
  api/bin/chainflip-ingress-egress-tracker/build.rs
  api/bin/chainflip-ingress-egress-tracker/src/main.rs
  api/bin/chainflip-ingress-egress-tracker/src/witnessing/dot.rs
  api/bin/chainflip-ingress-egress-tracker/src/witnessing/eth.rs
  api/bin/chainflip-lp-api/Cargo.toml
  api/bin/chainflip-lp-api/README.md
  api/bin/chainflip-lp-api/build.rs
  api/bin/chainflip-lp-api/src/main.rs
  engine/src/settings.rs
Labels: CFE

#4353 fix: btc witnesser test failing sometimes
  engine/src/witness/btc/btc_deposits.rs
Labels: CFE
