Repository chainflip-io/chainflip-backend, pull requests merged in 2024-05, with the labels that each got.

#4811 feat: Efficient Arbitrum witnessing (PRO-1098)
  api/bin/chainflip-ingress-egress-tracker/src/witnessing/eth.rs
  engine/src/evm/retry_rpc.rs
  engine/src/lib.rs
  engine/src/witness/arb.rs
  engine/src/witness/btc.rs
  engine/src/witness/common/chain_source/extension.rs
  engine/src/witness/common/chain_source/lag_safety.rs
  engine/src/witness/common/chunked_chain_source/chunked_by_vault/continuous.rs
  engine/src/witness/common/chunked_chain_source/chunked_by_vault/deposit_addresses.rs
  engine/src/witness/common/chunked_chain_source/chunked_by_vault/egress_items.rs
  engine/src/witness/common/epoch_source.rs
  engine/src/witness/eth.rs
  engine/src/witness/eth/state_chain_gateway.rs
  engine/src/witness/evm/contract_common.rs
  engine/src/witness/evm/erc20_deposits.rs
  engine/src/witness/evm/evm_deposits.rs
  engine/src/witness/evm/key_manager.rs
  engine/src/witness/evm/source.rs
  engine/src/witness/evm/vault.rs
  state-chain/chains/src/any.rs
  state-chain/chains/src/arb.rs
  state-chain/chains/src/btc.rs
  state-chain/chains/src/dot.rs
  state-chain/chains/src/eth.rs
  state-chain/chains/src/lib.rs
  state-chain/chains/src/mocks.rs
  state-chain/chains/src/none.rs
  state-chain/pallets/cf-chain-tracking/src/lib.rs
  state-chain/pallets/cf-ingress-egress/src/lib.rs
  state-chain/pallets/cf-vaults/src/lib.rs
  utilities/src/with_std/rle_bitmap.rs
Labels: CFE, State Chain

#4843 Engine version checks no longer needed for new engines
  .github/workflows/_03_release_checks.yml
  ci/scripts/check_engine_systemd_config.sh
Labels: non-breaking

#4844 chore: fix storage migration for ingress-egress pallet
  state-chain/pallets/cf-ingress-egress/src/migrations/add_boost_pools.rs
  state-chain/pallets/cf-ingress-egress/src/migrations/multiple_brokers.rs
  state-chain/pallets/cf-swapping/src/benchmarking.rs
Labels: non-breaking

#4854 chore: bump create pull request version
  .github/workflows/ci-cherry-pick.yml
Labels: non-breaking

#4864 fix: add `ca-certificates` to docker images 🐛
  ci/docker/development/chainflip-broker-api.Dockerfile
  ci/docker/development/chainflip-cli.Dockerfile
  ci/docker/development/chainflip-engine.Dockerfile
  ci/docker/development/chainflip-ingress-egress-tracker.Dockerfile
  ci/docker/development/chainflip-lp-api.Dockerfile
  ci/docker/development/chainflip-node.Dockerfile
  ci/docker/development/generate-genesis-keys.Dockerfile
  ci/docker/production/chainflip-broker-api.Dockerfile
  ci/docker/production/chainflip-cli.Dockerfile
  ci/docker/production/chainflip-engine.Dockerfile
  ci/docker/production/chainflip-ingress-egress-tracker.Dockerfile
  ci/docker/production/chainflip-lp-api.Dockerfile
  ci/docker/production/chainflip-node.Dockerfile
Labels: non-breaking

#4853 Boost bouncer commands and test
  bouncer/commands/add_boost_funds.ts
  bouncer/commands/create_boost_pools.ts
  bouncer/commands/new_swap.ts
  bouncer/commands/provide_liquidity.ts
  bouncer/commands/setup_boost_pools.ts
  bouncer/commands/stop_boosting.ts
  bouncer/shared/boost.ts
  bouncer/shared/broker_fee_collection.ts
  bouncer/shared/lp_api_test.ts
  bouncer/shared/new_swap.ts
  bouncer/shared/perform_swap.ts
  bouncer/shared/provide_liquidity.ts
  bouncer/shared/setup_boost_pools.ts
  bouncer/shared/setup_swaps.ts
  bouncer/shared/submit_runtime_upgrade.ts
  bouncer/shared/utils.ts
  bouncer/tests/all_concurrent_tests.ts
  bouncer/tests/boost_test.ts
  bouncer/tests/double_deposit.ts
  state-chain/pallets/cf-ingress-egress/src/lib.rs
Labels: Bouncer
