Repository chainflip-io/chainflip-backend, pull requests merged in 2024-03, with the labels that each got.

#4553 log meaningful message if docker login fails
  localnet/manage.sh
Labels: non-breaking

#4582 chore(bouncer): Update sdk to 1.2.1
  bouncer/commands/create_lp_pool.ts
  bouncer/commands/get_balance.ts
  bouncer/commands/go_bananas.ts
  bouncer/commands/new_swap.ts
  bouncer/commands/perform_swap.ts
  bouncer/commands/provide_liquidity.ts
  bouncer/commands/range_order.ts
  bouncer/commands/send.ts
  bouncer/commands/setup_swaps.ts
  bouncer/package.json
  bouncer/pnpm-lock.yaml
  bouncer/shared/approve_erc20.ts
  bouncer/shared/contract_swap.ts
  bouncer/shared/create_lp_pool.ts
  bouncer/shared/evm_deposits.ts
  bouncer/shared/fund_flip.ts
  bouncer/shared/fund_redeem.ts
  bouncer/shared/gaslimit_ccm.ts
  bouncer/shared/get_balance.ts
  bouncer/shared/get_dot_balance.ts
  bouncer/shared/get_erc20_balance.ts
  bouncer/shared/get_evm_native_balance.ts
  bouncer/shared/lp_api_test.ts
  bouncer/shared/new_swap.ts
  bouncer/shared/perform_swap.ts
  bouncer/shared/polkadot_runtime_update.ts
  bouncer/shared/provide_liquidity.ts
  bouncer/shared/range_order.ts
  bouncer/shared/redeem_flip.ts
  bouncer/shared/send.ts
  bouncer/shared/send_dot.ts
  bouncer/shared/send_erc20.ts
  bouncer/shared/send_evm.ts
  bouncer/shared/swapping.ts
  bouncer/shared/utils.ts
  bouncer/tests/broker_fee_collection_test.ts
Labels: non-breaking

#4589 chore: add notification on failed release build
  .github/workflows/_40_post_check.yml
Labels: non-breaking

#4605 fix: debug cli
  api/bin/chainflip-cli/src/settings.rs
Labels: non-breaking

#4615 chore: update chainspecs
  state-chain/chains/src/eth.rs
  state-chain/node/src/chain_spec/perseverance.rs
  state-chain/node/src/chain_spec/sisyphos.rs
Labels: non-breaking

#4584 feat: use swapping queue when swapping network fee for burn
  .cargo/config.toml
  bouncer/commands/upgrade_network.ts
  bouncer/shared/try_runtime_upgrade.ts
  state-chain/pallets/cf-pools/src/lib.rs
  state-chain/pallets/cf-pools/src/migrations.rs
  state-chain/pallets/cf-pools/src/mock.rs
  state-chain/pallets/cf-pools/src/tests.rs
  state-chain/pallets/cf-swapping/src/lib.rs
  state-chain/pallets/cf-swapping/src/tests.rs
  state-chain/runtime/src/lib.rs
  state-chain/traits/src/liquidity.rs
Labels: State Chain

#4633 fix: usdt should use new encoding not legacy
  state-chain/primitives/src/chains/assets.rs
Labels: State Chain

#4643 feat: add broker api connection limit option
  api/bin/chainflip-broker-api/src/main.rs
Labels: non-breaking

#4644 fix: remove unused cli command line options
  api/bin/chainflip-cli/src/settings.rs
Labels: non-breaking

#4664 logging: lp-api panic in submission watcher
  engine/src/state_chain_observer/client/extrinsic_api/signed/submission_watcher.rs
Labels: non-breaking

#4667 fix: submission watcher could confuse/lose track of submissions
  engine/src/state_chain_observer/client/extrinsic_api/signed/submission_watcher.rs
Labels: bug, non-breaking

#4674 fix: cf_pools_environment rpc encoding
  state-chain/custom-rpc/src/lib.rs
  state-chain/custom-rpc/src/snapshots/custom_rpc__test__environment_serialization.snap
Labels: bug, non-breaking

#4685 Add USDT to banana mode and update code to reflect new storage
  bouncer/commands/go_bananas.ts
Labels: non-breaking

#4694 fix: typo in the error message
  state-chain/primitives/src/chains/assets.rs
Labels: non-breaking, cherry-pick

#4707 fix: continuous adapter
  engine/src/witness/common/chunked_chain_source/chunked_by_vault/continuous.rs
Labels: non-breaking

#4710 chore: remove backcompat asset encoding from rpcs (and make them line up with newer Asset encoding)
  api/bin/chainflip-lp-api/src/main.rs
  api/lib/src/lp.rs
  api/lib/src/queries.rs
  bouncer/shared/lp_api_test.ts
  state-chain/custom-rpc/src/lib.rs
  state-chain/pallets/cf-lp/src/lib.rs
  state-chain/pallets/cf-pools/src/mock.rs
  state-chain/primitives/src/chains/assets.rs
  state-chain/runtime/src/lib.rs
  state-chain/runtime/src/runtime_apis.rs
  state-chain/traits/src/liquidity.rs
  state-chain/traits/src/mocks/lp_balance.rs
Labels: CLI / API
