Repository chainflip-io/chainflip-backend, pull requests merged in 2024-02, with the labels that each got.

#4511 fix: nicer formatting of dot addresses and payloads
  engine/src/dot/retry_rpc.rs
  engine/src/witness/dot.rs
Labels: non-breaking

#4524 fake
  .github/workflows/ci-cherry-pick.yml
Labels: non-breaking

#4498 feat: auto pick non-breaking changes
  .github/pull_request_template.md
  .github/workflows/ci-cherry-pick.yml
Labels: non-breaking

#4530 test
  .github/workflows/ci-cherry-pick.yml
Labels: non-breaking

#4531 test
  .github/workflows/ci-cherry-pick.yml
Labels: non-breaking

#4491 refactor: Remove RpcAsset (PRO-1187)
  Cargo.lock
  api/bin/chainflip-broker-api/src/main.rs
  api/bin/chainflip-cli/src/main.rs
  api/bin/chainflip-cli/src/settings.rs
  api/bin/chainflip-ingress-egress-tracker/src/witnessing/state_chain.rs
  api/bin/chainflip-lp-api/src/main.rs
  api/lib/src/lp.rs
  api/lib/src/queries.rs
  state-chain/custom-rpc/src/lib.rs
  state-chain/custom-rpc/src/snapshots/custom_rpc__test__environment_serialization.snap
  state-chain/custom-rpc/src/snapshots/custom_rpc__test__lp_serialization.snap
  state-chain/pallets/cf-swapping/src/tests.rs
  state-chain/primitives/Cargo.toml
  state-chain/primitives/src/chains/assets.rs
  state-chain/runtime/src/chainflip.rs
  state-chain/runtime/src/lib.rs
  state-chain/traits/src/mocks/swap_deposit_handler.rs
Labels: State Chain, refactor, CLI / API

#4503 fix: continuous adapter (PRO-684)
  engine/src/witness/common/chunked_chain_source/chunked_by_vault/continuous.rs
Labels: bug, CFE

#4567 chore: upgrade solana version
  .github/workflows/_40_post_check.yml
Labels: non-breaking

#4496 feat: store prewitnessed deposits with id
  engine/src/witness/start.rs
  state-chain/TROUBLESHOOTING.md
  state-chain/pallets/cf-ingress-egress/src/benchmarking.rs
  state-chain/pallets/cf-ingress-egress/src/lib.rs
  state-chain/pallets/cf-ingress-egress/src/mock_eth.rs
  state-chain/pallets/cf-ingress-egress/src/tests.rs
  state-chain/pallets/cf-ingress-egress/src/weights.rs
  state-chain/pallets/cf-witnesser/src/benchmarking.rs
  state-chain/pallets/cf-witnesser/src/lib.rs
  state-chain/pallets/cf-witnesser/src/weights.rs
  state-chain/primitives/src/lib.rs
  state-chain/runtime/src/chainflip.rs
  state-chain/traits/src/lib.rs
  state-chain/traits/src/mocks.rs
Labels: CFE, State Chain

#4547 feat: Relative Slippage Limits (PRO-1207)
  state-chain/amm/src/common.rs
  state-chain/amm/src/lib.rs
  state-chain/pallets/cf-pools/src/benchmarking.rs
  state-chain/pallets/cf-pools/src/lib.rs
  state-chain/pallets/cf-pools/src/tests.rs
  state-chain/pallets/cf-pools/src/weights.rs
  state-chain/pallets/cf-swapping/src/lib.rs
Labels: State Chain

#4552 feat: add boost lp account to bouncer and fund it on setup_swaps
  bouncer/commands/setup_swaps.ts
  bouncer/shared/provide_liquidity.ts
  localnet/init/keys/LP_BOOST
  state-chain/node/src/chain_spec/testnet.rs
Labels: non-breaking

#4574 Solana: update image to latest tag
  .cargo/config.toml
  contract-interfaces/sol-program-idls/download-sol-program-idls.sh
  contract-interfaces/sol-program-idls/v0.1.1/cf_tester.json
  contract-interfaces/sol-program-idls/v0.1.1/vault.json
  localnet/docker-compose.yml
Labels: non-breaking

#4586 chore: add origin to ccm failed
  state-chain/pallets/cf-swapping/src/lib.rs
  state-chain/pallets/cf-swapping/src/tests.rs
Labels: non-breaking

#4570 Chore/fix arbitrum deployment
  .cargo/config.toml
  bouncer/shared/eth_abis.ts
  contract-interfaces/eth-contract-abis/v1.1.2/CFTester.json
  contract-interfaces/eth-contract-abis/v1.1.2/Deposit_bytecode.json
  contract-interfaces/eth-contract-abis/v1.1.2/IAddressChecker.json
  contract-interfaces/eth-contract-abis/v1.1.2/IFLIP.json
  contract-interfaces/eth-contract-abis/v1.1.2/IKeyManager.json
  contract-interfaces/eth-contract-abis/v1.1.2/IStateChainGateway.json
  contract-interfaces/eth-contract-abis/v1.1.2/IVault.json
  localnet/docker-compose.yml
Labels: non-breaking
